#!/usr/bin/env python3
"""Bundle the whole site into one self-contained HTML file.

The site is deliberately multi-page: nine documents per locale, each one a real
URL. That is right for the web and wrong for anywhere a demo has to be a single
file with no external requests allowed. This script produces that single file
without forking the codebase — the CSS, JS and data are the site's own, and the
page bodies are lifted out of the generated HTML, so the demo cannot drift away
from what build.py produces.

    python3 tools/fetch-fonts.py   # once, needs network
    python3 tools/build.py
    python3 tools/bundle.py        # writes dist/masar-demo.html

What changes in the bundle, and only in the bundle:

  * Navigation becomes hash routing (#/courses.html?subject=finance). Anchor
    clicks are intercepted; the address bar still carries the filter state, so
    a filtered view is still a link you can send.
  * app.js reads location.search and calls history.replaceState. The bundle
    wraps it as a function of (location, history) and passes shims that read
    and write the hash instead. The file itself is not modified.
  * Fonts arrive as @font-face data URIs (see tools/fetch-fonts.py).

The output is a body fragment — no <html>/<head>/<body> of its own — because
that is what the artifact host expects to wrap.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(HERE, "dist")
OUT = os.path.join(DIST, "masar-demo.html")

PAGES = ["index.html", "courses.html", "course.html", "schools.html", "school.html",
         "lists.html", "list.html", "about.html", "contact.html"]


def read(*parts):
    path = os.path.join(HERE, *parts)
    if not os.path.exists(path):
        sys.exit("Missing {} — run tools/build.py (and tools/fetch-fonts.py) first.".format(path))
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def grab(pattern, html, what):
    m = re.search(pattern, html, re.S)
    if not m:
        sys.exit("Could not find {} — has the page shell in build.py changed?".format(what))
    return m.group(1) if m.groups() else m.group(0)


def js(value):
    """Embed a Python value as JS, safe to sit inside a <script> block."""
    return json.dumps(value, ensure_ascii=False).replace("</", "<\\/")


def main():
    # --- page bodies and titles, per locale -------------------------------
    bodies, titles = {}, {}
    for page in PAGES:
        bodies[page], titles[page] = {}, {}
        for lang in ("en", "ar"):
            html = read("ar", page) if lang == "ar" else read(page)
            bodies[page][lang] = grab(r'<main id="main">(.*?)</main>', html, "the <main> block")
            titles[page][lang] = grab(r"<title>(.*?)</title>", html, "the <title>")

    # --- chrome, per locale -----------------------------------------------
    chrome = {}
    for lang in ("en", "ar"):
        html = read("ar", "index.html") if lang == "ar" else read("index.html")
        chrome[lang] = {
            "skip": grab(r'(<a class="skip-link".*?</a>)', html, "the skip link"),
            "header": grab(r'(<header class="site-header">.*?</header>)', html, "the header"),
            "footer": grab(r'(<footer class="site-footer">.*?</footer>)', html, "the footer"),
            "drawer": grab(r'(<div class="drawer-backdrop".*?</aside>)', html, "the shortlist drawer"),
        }

    fonts = read("dist", "fonts.css")
    site_css = read("assets", "css", "site.css")
    data_js = read("assets", "js", "data.js")
    i18n_js = read("assets", "js", "i18n.js")
    app_js = read("assets", "js", "app.js")

    # app.js is an IIFE over the globals it needs; re-open it so the bundle can
    # hand it a location/history pair that speaks hash routes.
    if not app_js.startswith("/*"):
        sys.exit("app.js does not start with its header comment — check the wrapper assumptions.")
    wrapped, n = re.subn(r"\(function \(\) \{", "(function (location, history) {", app_js, count=1)
    if n != 1:
        sys.exit("Could not re-open app.js's IIFE — its opening line has changed.")
    wrapped, n = re.subn(r"\}\)\(\);\s*$", "})(window.__masarLocation, window.__masarHistory);\n", wrapped)
    if n != 1:
        sys.exit("Could not close app.js's IIFE — its final line has changed.")

    out = """<style>
/* ==========================================================================
   Masar — single-file demo build. Generated by tools/bundle.py; edit the
   sources under assets/ and tools/build.py, not this file.
   ========================================================================== */
{fonts}
{site_css}

/* Demo-only: the host page supplies the document chrome, so give the bundle
   the same page background the real site sets on <html>. */
html {{ background: var(--bg); }}
</style>

<script>
  /* Locale and theme are decided before anything renders: i18n.js reads
     <html lang> at load, and a late theme switch would flash the page. */
  (function () {{
    var lang = 'en', theme = null;
    try {{
      lang = localStorage.getItem('masar:lang') === 'ar' ? 'ar' : 'en';
      theme = localStorage.getItem('masar:theme');
    }} catch (e) {{}}
    if (!theme) {{
      theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }}
    var root = document.documentElement;
    root.setAttribute('lang', lang);
    root.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');
    root.setAttribute('data-theme', theme);
  }})();
</script>

<div data-masar-skip></div>
<div data-masar-chrome-top></div>
<main id="main"></main>
<div data-masar-chrome-bottom></div>

<script>
{data_js}
</script>

<script>
/* ==========================================================================
   Demo router. Turns the site's nine documents into hash routes and gives
   app.js a location/history pair that reads and writes those routes.
   ========================================================================== */
(function () {{
  'use strict';

  var BODIES = {bodies};
  var TITLES = {titles};
  var CHROME = {chrome};
  var LANG = document.documentElement.lang === 'ar' ? 'ar' : 'en';
  var HOME = 'index.html';

  function route() {{
    var hash = '';
    try {{ hash = decodeURIComponent(location.hash); }} catch (e) {{ hash = location.hash; }}
    hash = hash.replace(/^#\\/?/, '');
    var cut = hash.indexOf('?');
    var page = cut === -1 ? hash : hash.slice(0, cut);
    return {{
      page: Object.prototype.hasOwnProperty.call(BODIES, page) ? page : HOME,
      query: cut === -1 ? '' : hash.slice(cut)
    }};
  }}

  function href(page, query) {{ return '#/' + page + (query || ''); }}

  /* app.js asks for location.search and calls history.replaceState with either
     '?query' or a pathname; both are answered against the current hash. */
  window.__masarLocation = {{
    get search() {{ return route().query; }},
    get pathname() {{ return route().page; }},
    get hash() {{ return location.hash; }},
    get href() {{ return location.href; }}
  }};
  window.__masarHistory = {{
    replaceState: function (state, title, url) {{
      var query = (typeof url === 'string' && url.charAt(0) === '?') ? url : '';
      history.replaceState(state, title, href(route().page, query));
    }},
    pushState: function (state, title, url) {{
      var query = (typeof url === 'string' && url.charAt(0) === '?') ? url : '';
      history.pushState(state, title, href(route().page, query));
    }}
  }};

  function paintChrome() {{
    document.querySelector('[data-masar-skip]').innerHTML = CHROME[LANG].skip;
    document.querySelector('[data-masar-chrome-top]').innerHTML = CHROME[LANG].header;
    document.querySelector('[data-masar-chrome-bottom]').innerHTML =
      CHROME[LANG].footer + CHROME[LANG].drawer;
  }}

  function paintPage(scroll) {{
    var r = route();
    document.getElementById('main').innerHTML = BODIES[r.page][LANG];
    document.title = TITLES[r.page][LANG];
    document.querySelectorAll('.main-nav a').forEach(function (a) {{
      var target = (a.getAttribute('href') || '').split('?')[0];
      if (target === r.page) a.setAttribute('aria-current', 'page');
      else a.removeAttribute('aria-current');
    }});
    var nav = document.getElementById('main-nav');
    if (nav) nav.removeAttribute('data-open');
    if (window.MASAR_APP) window.MASAR_APP.mount();
    if (scroll) window.scrollTo({{ top: 0, behavior: 'instant' }});
  }}

  /* Every in-site link is a document link in the real site; here they route. */
  document.addEventListener('click', function (e) {{
    var a = e.target.closest ? e.target.closest('a[href]') : null;
    if (!a || e.metaKey || e.ctrlKey || e.shiftKey || e.button) return;
    var raw = a.getAttribute('href') || '';

    if (a.hasAttribute('data-lang-switch')) {{
      e.preventDefault();
      /* i18n.js binds its locale at load, so switching reloads the page. The
         hash — and with it the current page and its filters — survives. */
      try {{ localStorage.setItem('masar:lang', LANG === 'en' ? 'ar' : 'en'); }} catch (err) {{}}
      location.reload();
      return;
    }}

    var m = raw.match(/^(?:\\.\\.\\/|ar\\/)?([a-z-]+\\.html)(\\?.*)?$/);
    if (!m) return;
    e.preventDefault();
    if (!Object.prototype.hasOwnProperty.call(BODIES, m[1])) return;
    history.pushState({{}}, '', href(m[1], m[2] || ''));
    paintPage(true);
  }});

  window.addEventListener('popstate', function () {{ paintPage(false); }});

  paintChrome();
  paintPage(false);   /* app.js boots itself next and mounts this body */
}})();
</script>

<script>
{i18n_js}
</script>

<script>
{app_js}
</script>
""".format(
        fonts=fonts,
        site_css=site_css,
        data_js=data_js,
        i18n_js=i18n_js,
        app_js=wrapped,
        bodies=js(bodies),
        titles=js(titles),
        chrome=js(chrome),
    )

    os.makedirs(DIST, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("Wrote {} ({:.0f} KB)".format(os.path.relpath(OUT, HERE), os.path.getsize(OUT) / 1024))


if __name__ == "__main__":
    main()
