#!/usr/bin/env python3
"""Download the site's webfonts and emit a self-contained @font-face stylesheet.

The single-file demo (tools/bundle.py) is published to a host that blocks
requests to external origins, so a <link> to Google Fonts there would fail
silently and drop the page to system fonts. This fetches the woff2 files once
and writes them into dist/fonts.css as data: URIs.

    python3 tools/fetch-fonts.py     # needs network; writes dist/fonts.css

Only the subsets the site actually renders are kept — latin for the English
face, latin + arabic for the Arabic one — because base64 costs a third on top
of the file size and the rest would never be used.
"""

import base64
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "dist", "fonts.css")

# A modern UA is what makes Google serve woff2 instead of ttf.
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/124.0.0.0 Safari/537.36")

# Weights are exactly the ones site.css asks for — 400/700/800 for UI text,
# 600/700 for the serif display, and the Arabic face doing both jobs. Subset
# names are matched exactly, so latin-ext (which this site never renders)
# does not sneak in and double the payload.
# Manrope and Newsreader are variable fonts: asking for a weight *range*
# returns one file covering it, where listing weights individually returns a
# full copy of the variable font per weight (Newsreader is 129 KB a time).
# IBM Plex Sans Arabic is static, so its weights are listed. Its latin subset
# is skipped — site.css puts Manrope behind it in the Arabic stack, so Latin
# runs inside Arabic text fall through to a face already being loaded.
FAMILIES = [
    ("Manrope:wght@400..800", {"latin"}),
    ("Newsreader:opsz,wght@6..72,600..700", {"latin"}),
    ("IBM+Plex+Sans+Arabic:wght@400;600;700", {"arabic"}),
]


def get(url, headers=None):
    req = urllib.request.Request(url, headers=headers or {"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as fh:
        return fh.read()


def main():
    chunks = ["/* Generated by tools/fetch-fonts.py — do not edit by hand. */\n"]
    total = 0

    for query, wanted in FAMILIES:
        url = "https://fonts.googleapis.com/css2?family={}&display=swap".format(query)
        css = get(url).decode("utf-8")

        # Google's CSS is a run of "/* subset */ @font-face {...}" blocks.
        blocks = re.findall(r"/\*\s*([\w\-\[\]]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
        if not blocks:
            sys.exit("No @font-face blocks parsed for {} — did the CSS format change?".format(query))

        kept = 0
        for subset, block in blocks:
            if subset not in wanted:
                continue
            m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not m:
                continue
            data = get(m.group(1), {"User-Agent": UA})
            total += len(data)
            uri = "data:font/woff2;base64," + base64.b64encode(data).decode("ascii")
            chunks.append(block.replace(m.group(1), uri) + "\n")
            kept += 1
        print("{:<44} {} subsets".format(query.split(":")[0], kept))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(chunks))
    print("\nWrote {} ({:.0f} KB of font data, {:.0f} KB encoded)".format(
        os.path.relpath(OUT, HERE), total / 1024, os.path.getsize(OUT) / 1024))


if __name__ == "__main__":
    main()
